apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: iotproject
  name: iotproject-app
spec:
  project: iot-project
  source:
    repoURL: "https://github.com/aabelque/aabelque-IoT.git"
    targetRevision: master
    path: app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
